version: '3.4'
services:
  picsql:
    container_name: picsql
    restart: always
    hostname: mysql
    volumes:
      - ./db:/var/lib/mysql
    build:
      context: .
      dockerfile: mysql.Dockerfile    
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_USER=api_user
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=picpay_teste
    ports:
      - "3351:3306"
  pic-rabbit:
    image: "rabbitmq:3-management"
    container_name: "pic-rabbit"
    hostname: "pic-rabbit"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    labels:
      NAME: "rabbitmq1"
    ports:
      - "5672:5672"
      - "15672:15672"
  elasticsearch:
    image: elastic/elasticsearch:6.2.2
    container_name: elastic
    hostname: elastic
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./es:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=elastic
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=elastic
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  picpay-test:
    container_name: "picpay-test"
    restart: always
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./picpay-teste-backend:/picpay-teste-backend
      - ~/.m2:/root/.m2
    environment:
      - MYSQL_DATASOURCE=picsql:3306
      - SPRING_DATASOURCE_PASSWORD=root
      - RABBIT_HOST=pic-rabbit
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASS=rabbitmq
      - CLUSTER_NAME=elastic
      - CLUSTER_NODES=elastic:9300
    ports:
      - "8080:8080"
    depends_on:
      - pic-rabbit
      - picsql
      - elasticsearch